# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
(38) $env_var\
$username\
$localip\
$os\
$hostname\
$directory\
$memory_usage\
$battery\
$time
$character"""

[os]
format = "on [$symbol]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Windows = "🪟"

# Change the default prompt characters
[character]
success_symbol = " [\u276f_:](38)"
error_symbol = " [❌](38)"

[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white)'
variable = "STARSHIP_DISTRO"
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = true  # disable in powershell
show_always = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " "
read_only_style = "197"
read_only = " 🔒 "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "

[terraform]
format = "via [ terraform $version]($style) 壟 [$workspace]($style) "

[vagrant]
format = "via [⍱vagrant $version]($style) "

[docker_context]
format = "via [🐳$context](bold blue) "

[helm]
format = "via [ $version](bold purple) "

[python]
symbol = " "
python_binary = "python3"

[nodejs]
format = "via [ $version](bold green) "
disabled = true

[ruby]
format = "via [ $version]($style) "

[kubernetes]
format = 'on [ $context\($namespace\)](bold green) '
disabled = false
[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"

[azure]
disabled = true
format = "on [$symbol($subscription)]($style) "
symbol = "ﴃ "
style = "blue bold"

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️(38) '
discharging_symbol = '💀 '
[[battery.display]]
threshold = 40
style = 'bold red'

[localip]
ssh_only = false
format = '@[$localipv4]($style) '
disabled = false

[time]
disabled = false
format = ' 🕙 at [$time]($style)'
time_format = '%T'
utc_time_offset = 'local'
time_range = '08:00:00-20:00:00'

[memory_usage]
disabled = false
threshold = -1
symbol = '🐏'
style = 'bold dimmed white'
format = '$symbol [${ram_pct}]($style)'

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](bold green) '
trim_at = '.tricomputers.co.uk'
disabled = false
